---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 5a9a3cdfd3b21ea694a863a86670329cc92449d9
    fabric8.io/git-branch: openshift
    fabric8.io/git-url: git@github.com:slowtrailrunner/demo-app.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-app
    fabric8.io/scm-tag: HEAD
  labels:
    app: demo-app
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.sre.demo
  name: demo-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: demo-app
    provider: fabric8
    group: com.sre.demo
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 5a9a3cdfd3b21ea694a863a86670329cc92449d9
        fabric8.io/git-branch: openshift
        fabric8.io/scm-tag: HEAD
        fabric8.io/git-url: git@github.com:slowtrailrunner/demo-app.git
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-app
      labels:
        app: demo-app
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: com.sre.demo
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: demo-app:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: demo-app:latest
    type: ImageChange
