---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 5a9a3cdfd3b21ea694a863a86670329cc92449d9
    fabric8.io/git-branch: openshift
    fabric8.io/git-url: git@github.com:slowtrailrunner/demo-app.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-app
    fabric8.io/scm-tag: HEAD
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: demo-app
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.sre.demo
  name: demo-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-app
    provider: fabric8
    group: com.sre.demo
